### ISSUE TITLE
Symbolic Alchemy results?

### ISSUE THREAD

**Issue by carlosluis** [UT-Austin-RPL/amago#16]
Great work! Thanks for open-sourcing the code.

I see there's integration with Alchemy (symbolic), but no reported results in the paper. 

Have you tried running AMAGO on it? I've always wondered if better sequence models are able to learn the complex latent structure of tasks.

Cheers!

**Comment by jakegrigsby** [comment]
Thanks! Yeah I added alchemy after the paper submission as a fun example and future project. 

For context, a randomly initialized policy gets a return in the 15-20 range with a random heuristic and DM's RL baselines in the 140-150s:

<img width="412" alt="Screen Shot 2024-01-12 at 1 01 40 PM" src="https://github.com/UT-Austin-RPL/amago/assets/33582737/7a3393a6-5360-47a6-b11f-b1fef56e39d4">

When I run AMAGO with close to default hyperparameters I usually see 100-120 range. If I scale up the number of parallel actors (like 36) and initialize the replay buffer to be full of trajectories from a previous trial I get into the high 140s. However, I've also seen scores above 155 for a feedforward `TrajectoryEncoder` model (that has no memory) so my best guess is that the bottleneck is more on the credit assignment / exploration side of things than memory at current performance.

I think there'd be a lot to learn from an extensive hyperparameter sweep on this domain and I plan on doing that soon.

**Comment by carlosluis** [comment]
Thanks for the reference scores, much appreciated!

I'll close the issue
