### ISSUE TITLE
Inference on CPU

### ISSUE THREAD

**Issue by SeeYaaa** [UT-Austin-RPL/amago#20]
Is it possible to run the trained agent on CPU only?

**Comment by jakegrigsby** [comment]
It wasn't possible but it was a pretty quick fix. See my note in #21 though... this only works for the pure pytorch sequence models (TrajEncoder) like RNNs/FeedForward. 

In most of the example scripts you can load a checkpoint on the CPU with `--ckpt <epoch num> --gpu -1`

And in the `amago.experiment.Experiment` object it's `gpu=-1`. 

This supports both training and inference, although training on the cpu is a huge slowdown of course.
