### ISSUE TITLE
Question regarding Mamba

### ISSUE THREAD

**Issue by CTP314** [UT-Austin-RPL/amago#29]
Thank you for your interesting work on RL for CMDPs. I noticed the addition of MAMBA to the repository, which wasn't mentioned in the paper. Are there any plans to release the results for AMAGO-MAMBA to the public?
Thanks for your contributions once again.

**Comment by jakegrigsby** [comment]
Hi, thanks!

Yes I added Mamba many months after the experiments for the paper were done. A nice thing about how the repo is setup is that it's pretty straightforward to use any seq2seq model, even though the paper focuses on Transformers specifically.

I've only played around with Mamba a little bit as a test. Here are the results that I have, but a lot more experimentation is needed:

![mamba_eval](https://github.com/UT-Austin-RPL/amago/assets/33582737/253c6e93-fd63-4fc6-893e-83a3bd5c2c4e)

Mamba is super cool, but I think RL is a difficult area for state space models in general. Relying on RL credit assignment to learn hidden state reads/writes has always been hard, even though Mamba seems like a big improvement in that area. Transformers only need to use RL to learn recall of the sequence at each timestep which is much simpler. So far I think the sequences would have to be very long - or inference speed would have to be a major constraint - to justify not using a Transformer.

**Comment by CTP314** [comment]
> Hi, thanks!
> 
> Yes I added Mamba many months after the experiments for the paper were done. A nice thing about how the repo is setup is that it's pretty straightforward to use any seq2seq model, even though the paper focuses on Transformers specifically.
> 
> I've only played around with Mamba a little bit as a test. Here are the results that I have, but a lot more experimentation is needed:
> 
> ![mamba_eval](https://private-user-images.githubusercontent.com/33582737/316118240-253c6e93-fd63-4fc6-893e-83a3bd5c2c4e.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExNDM5NjIsIm5iZiI6MTcxMTE0MzY2MiwicGF0aCI6Ii8zMzU4MjczNy8zMTYxMTgyNDAtMjUzYzZlOTMtZmQ2My00ZmM2LTg5M2UtODNhM2JkNWMyYzRlLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMlQyMTQxMDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNDY0NjE3YjkxZWI0OTFhOGRjM2Q3YmY4YzMzOTFiY2FkNDQ4MzhlZmYxN2MxMTMzZmI2NDIzYWEyMmM5NWM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nTMnI7lXg4xY1nsHBXDaGCl9iEj2Sz2XeB4UcbI-pNc)
> 
> Mamba is super cool, but I think RL is a difficult area for state space models in general. Relying on RL credit assignment to learn hidden state reads/writes has always been hard, even though Mamba seems like a big improvement in that area. Transformers only need to use RL to learn recall of the sequence at each timestep which is much simpler. So far I think the sequences would have to be very long - or inference speed would have to be a major constraint - to justify not using a Transformer.


The tasks demonstrated in POPGym heavily test the model's ability to handle copying. For transformers, it's just a matter of retrieval within the context, whereas for recurrent structures, it requires reconstructing all information from a hidden state. The results you presented nicely validate this point. However, in some recent SSM + RL works such as [R2I](https://openreview.net/forum?id=1vDArHJ68h) they have demonstrated scores above 0.5 on these tasks in POPGym (though still not as good as AMAGO). The differences between their results and yours are worth considering. Perhaps AMAGO is better suited for transformers while Dreamer is more suitable for recurrent structures?

Additionally, I have some questions regarding the performance of key-to-door. In the paper, AMAGO achieves scores of over 40, but the baseline shown in the images is only 12. How did this difference arise?

**Comment by jakegrigsby** [comment]
Yes I totally agree that POPGym is especially well suited for Transformers. Not sure on the Transformer/AMAGO vs. RNN/Dreamer comparison... I'd imagine Transformer world models would have a similar advantage when predicting dynamics of memory intensive envs. But I think it will take a Dreamer-like engineering effort to find out if that's true in this setting. Hopefully future work.  




The performance gap you reference is just caused by a difference in timestep budget. In the figure above i'm taking the score of the Transformer after 7M frames; in the paper the x axis is much longer.

**Comment by CTP314** [comment]
> Yes I totally agree that POPGym is especially well suited for Transformers. Not sure on the Transformer/AMAGO vs. RNN/Dreamer comparison... I'd imagine Transformer world models would have a similar advantage when predicting dynamics of memory intensive envs. But I think it will take a Dreamer-like engineering effort to find out if that's true in this setting. Hopefully future work.
> 
> The performance gap you reference is just caused by a difference in timestep budget. In the figure above i'm taking the score of the Transformer after 7M frames; in the paper the x axis is much longer.

Thank you for your response! Your work is very interesting. My questions have been mostly answered.
