### ISSUE TITLE
Can not find Q/K/V sigmaReparam Linear Block

### ISSUE THREAD

**Issue by daehwa00** [UT-Austin-RPL/amago#36]
![image](https://github.com/user-attachments/assets/60f0606e-6cf3-4a04-adea-74ea73f9f340)

First, thank you for publishing your great code.

According to the figure on page 20 of the paper, there should be a pre-norm followed by a Q/K/V sigmaReparam Linear, but it doesn't seem to be implemented in your code and goes straight to the Attention Block.
Am I seeing things correctly?

Thank you :)

**Comment by jakegrigsby** [comment]
Hi @daehwa00, the query/key/value generation is done as part of the `AttentionLayer` inside a `TransformerLayer`

https://github.com/UT-Austin-RPL/amago/blob/cb0a86eaba9ae4bcd6dee828cda87999acd5731e/amago/nets/transformer.py#L142-L164


The above code handles "Q/K/V sigmaReparam Linear" and "Causal Headscale Flash Attention", while the code in your screenshot handles the first norm and everything from the second norm onwards to the output.


<img width="459" alt="Screen Shot 2024-07-26 at 6 57 21 PM" src="https://github.com/user-attachments/assets/dce9e6ec-26cd-4139-9ee7-dd38f20d8625">

Hopefully that clears things up. Thanks for checking out the paper

**Comment by daehwa00** [comment]
Thank you!
